-- Proyectos de inversión (edificios con múltiples unidades).
-- Aplicado como migración `create_proyectos` en Supabase.

CREATE TABLE IF NOT EXISTS public.proyectos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  nombre text NOT NULL,
  inmobiliaria text,
  direccion text,
  comuna_id integer REFERENCES public.comunas(id),
  lat numeric,
  lng numeric,
  descripcion text,
  entrega text,
  pisos integer,
  ascensores integer,
  precio_desde_uf numeric,
  dscto_max numeric,
  bono_pie_max numeric,
  pie_en_cuotas boolean NOT NULL DEFAULT false,
  reserva_clp integer,
  financiamiento_pie text,
  arriendo_garantizado text,
  otros_beneficios text,
  cap_rate numeric,
  puntaje numeric,
  piscina boolean NOT NULL DEFAULT false,
  gimnasio boolean NOT NULL DEFAULT false,
  quincho boolean NOT NULL DEFAULT false,
  lavanderia boolean NOT NULL DEFAULT false,
  sala_multiuso boolean NOT NULL DEFAULT false,
  areas_verdes boolean NOT NULL DEFAULT false,
  pet_zone boolean NOT NULL DEFAULT false,
  renta_corta boolean NOT NULL DEFAULT false,
  eco_friendly boolean NOT NULL DEFAULT false,
  estado text NOT NULL DEFAULT 'borrador'
    CHECK (estado IN ('borrador', 'publicado', 'agotado'))
);

CREATE TABLE IF NOT EXISTS public.proyectos_unidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id bigint NOT NULL REFERENCES public.proyectos(id) ON DELETE CASCADE,
  numero text,
  tipologia text NOT NULL,
  dormitorios integer NOT NULL DEFAULT 0,
  banos integer NOT NULL DEFAULT 1,
  orientacion text,
  m2_total numeric,
  m2_ponderado numeric,
  precio_lista_uf numeric NOT NULL,
  dscto numeric NOT NULL DEFAULT 0,
  precio_final_uf numeric NOT NULL,
  arriendo_clp integer,
  cap_rate numeric,
  disponible boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.proyectos_imagenes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  proyecto_id bigint NOT NULL REFERENCES public.proyectos(id) ON DELETE CASCADE,
  url text NOT NULL,
  orden integer DEFAULT 0,
  es_portada boolean DEFAULT false
);

CREATE INDEX IF NOT EXISTS proyectos_user_id_idx ON public.proyectos(user_id);
CREATE INDEX IF NOT EXISTS proyectos_comuna_id_idx ON public.proyectos(comuna_id);
CREATE INDEX IF NOT EXISTS proyectos_estado_idx ON public.proyectos(estado);
CREATE INDEX IF NOT EXISTS proyectos_unidades_proyecto_id_idx ON public.proyectos_unidades(proyecto_id);
CREATE INDEX IF NOT EXISTS proyectos_imagenes_proyecto_id_idx ON public.proyectos_imagenes(proyecto_id);

ALTER TABLE public.proyectos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proyectos_unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proyectos_imagenes ENABLE ROW LEVEL SECURITY;

-- proyectos
CREATE POLICY "Public can read published projects" ON public.proyectos
  FOR SELECT USING (estado IN ('publicado', 'agotado'));
CREATE POLICY "Owners can read own projects" ON public.proyectos
  FOR SELECT TO authenticated USING ((select auth.uid()) = user_id);
CREATE POLICY "Owners can insert own projects" ON public.proyectos
  FOR INSERT TO authenticated WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Owners can update own projects" ON public.proyectos
  FOR UPDATE TO authenticated
  USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Owners can delete own projects" ON public.proyectos
  FOR DELETE TO authenticated USING ((select auth.uid()) = user_id);

-- proyectos_unidades y proyectos_imagenes: heredan visibilidad del proyecto padre
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['proyectos_unidades', 'proyectos_imagenes'] LOOP
    EXECUTE format($f$
      CREATE POLICY "Public can read %1$s of published projects" ON public.%1$I
        FOR SELECT USING (EXISTS (SELECT 1 FROM public.proyectos p
          WHERE p.id = %1$I.proyecto_id AND p.estado IN ('publicado', 'agotado')));
      CREATE POLICY "Owners can read %1$s" ON public.%1$I
        FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.proyectos p
          WHERE p.id = %1$I.proyecto_id AND p.user_id = (select auth.uid())));
      CREATE POLICY "Owners can insert %1$s" ON public.%1$I
        FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.proyectos p
          WHERE p.id = %1$I.proyecto_id AND p.user_id = (select auth.uid())));
      CREATE POLICY "Owners can update %1$s" ON public.%1$I
        FOR UPDATE TO authenticated
        USING (EXISTS (SELECT 1 FROM public.proyectos p
          WHERE p.id = %1$I.proyecto_id AND p.user_id = (select auth.uid())))
        WITH CHECK (EXISTS (SELECT 1 FROM public.proyectos p
          WHERE p.id = %1$I.proyecto_id AND p.user_id = (select auth.uid())));
      CREATE POLICY "Owners can delete %1$s" ON public.%1$I
        FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.proyectos p
          WHERE p.id = %1$I.proyecto_id AND p.user_id = (select auth.uid())));
    $f$, t);
  END LOOP;
END $$;

-- Plan de pago ("Detalle del pago"), migración `proyectos_plan_de_pago`.
-- El pie después de entrega no se guarda: es el saldo del pie menos abono y pie antes de entrega.
ALTER TABLE public.proyectos
  ADD COLUMN IF NOT EXISTS pie_pct numeric NOT NULL DEFAULT 0.2,
  ADD COLUMN IF NOT EXISTS abono_pct numeric NOT NULL DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS abono_forma text NOT NULL DEFAULT 'Transferencia al contado',
  ADD COLUMN IF NOT EXISTS pie_antes_pct numeric NOT NULL DEFAULT 0.05,
  ADD COLUMN IF NOT EXISTS pie_antes_cuotas integer NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS pie_antes_forma text NOT NULL DEFAULT 'Cuotas',
  ADD COLUMN IF NOT EXISTS pie_despues_cuotas integer NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS pie_despues_forma text NOT NULL DEFAULT 'Financiamiento externo';
